'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Game}=require('../lib/game');
function fixture(){const game=new Game({chooseIndex:()=>0,dice:()=>1});for(let i=0;i<2;i++)game.join('s'+i,{nombre:'Usuario '+i,userId:'usuario_'+i,sessionToken:String(i).repeat(64),sala:'AVISOS',crear:i===0});const r=game.rooms.AVISOS;const act=(i,event,data={})=>game.action('s'+i,event,{turnoId:r.turnoId,...data});act(0,'iniciarPartida',{monopolio:false});for(const player of r.jugadores)player.dinero=1000;return{game,r,act,a:r.jugadores[0],b:r.jugadores[1]};}
test('avisos: préstamo y amortización indican usuario, FMI e importe real',()=>{const {r,act}=fixture();act(0,'pedirPrestamo');let item=r.interacciones.at(-1);assert.equal(item.origen,'FMI');assert.equal(item.destino,'Usuario 0');assert.equal(item.accion,'Préstamo');assert.equal(item.monto,5000);act(0,'pagarDeuda');item=r.interacciones.at(-1);assert.equal(item.origen,'Usuario 0');assert.equal(item.destino,'FMI');assert.equal(item.accion,'Amortización');assert.equal(item.monto,5000);});
test('avisos: la renta solo aparece al pagar, una vez y para el dueño correcto',()=>{const {game,r,act,a,b}=fixture();game.payment(r,a,200,'Renta de Cobre',b.id,false);assert.equal(r.interacciones.length,0);act(0,'responderDecisionPago',{decisionId:r.pendiente.id,usarOro:false});assert.equal(r.interacciones.length,1);const item=r.interacciones[0];assert.equal(item.origen,a.nombre);assert.equal(item.destino,b.nombre);assert.equal(item.monto,200);assert.equal(item.accion,'Pago de renta');assert.equal(item.detalle,'Renta de Cobre');assert.equal(a.dinero,800);assert.equal(b.dinero,1200);});
test('avisos: pago en oro muestra un lingote y no simula un pago de efectivo',()=>{const {game,r,act,a}=fixture();game.payment(r,a,100,'Intereses FMI');act(0,'responderDecisionPago',{decisionId:r.pendiente.id,usarOro:true});assert.equal(r.interacciones.length,1);assert.equal(r.interacciones[0].monto,null);assert.equal(r.interacciones[0].destino,'FMI');assert.match(r.interacciones[0].detalle,/1 lingote/);assert.equal(a.dinero,1000);});
test('avisos: intercambio aceptado resume ambas partes sin duplicar cobros',()=>{const {game,r,act,a,b}=fixture();game.transfer(r,game.sur(r,'Cobre'),b.id);act(0,'proponerComercio',{destinatarioId:b.id,entrego:[],recibo:['Cobre'],pago:500,cobro:0});assert.equal(r.interacciones.length,0);act(1,'responderComercio',{decisionId:r.pendiente.id,aceptar:true});assert.equal(r.interacciones.length,1);const item=r.interacciones[0];assert.equal(item.accion,'Intercambio aceptado');assert.equal(item.origen,a.nombre);assert.equal(item.destino,b.nombre);assert.match(item.detalle,/Cobre/);assert.match(item.detalle,/\$500/);});
test('avisos: caja de alianza no duplica el movimiento y el historial es limitado y recuperable',()=>{const {game,r,a,b}=fixture();a.alianzaId=b.alianzaId='alianza';game.money(r,a,100);assert.equal(r.interacciones.length,1);assert.match(r.interacciones[0].destino,/alianza/);for(let i=0;i<70;i++)game.money(r,a,1);assert.equal(r.interacciones.length,60);assert.equal(new Set(r.interacciones.map(e=>e.id)).size,60);const restored=new Game({rooms:structuredClone(game.rooms)});assert.deepEqual(restored.state(restored.rooms.AVISOS).interacciones,r.interacciones);});

test('oro: la renta transfiere el lingote al propietario sin cambiar efectivo',()=>{const {game,r,act,a,b}=fixture();const before=[a.oro,b.oro];game.payment(r,a,500,'Renta de Caramelos',b.id);const id=r.pendiente.id;act(0,'responderDecisionPago',{decisionId:id,usarOro:true});assert.equal(a.oro,before[0]-1);assert.equal(b.oro,before[1]+1);assert.equal(a.dinero,1000);assert.equal(b.dinero,1000);assert.equal(r.interacciones.at(-1).destino,b.nombre);assert.throws(()=>act(0,'responderDecisionPago',{decisionId:id,usarOro:true}));assert.equal(b.oro,before[1]+1);});
test('12 de Octubre: pierde un lingote solo quien cae, nunca oro negativo',()=>{const {game,r,a,b}=fixture();a.oro=2;b.oro=3;game.land(r,a,32);assert.equal(a.oro,1);assert.equal(b.oro,3);a.oro=0;game.land(r,a,32);assert.equal(a.oro,0);});
test('12 de Octubre: una alianza pierde un solo lingote de su caja compartida',()=>{const {game,r,a,b}=fixture();a.alianzaId=b.alianzaId='union';a.oro=b.oro=4;game.land(r,a,32);assert.equal(a.oro,3);assert.equal(b.oro,3);});
test('Fuga: espera una tirada autorizada, cobra una vez y publica el dado sin mover ficha',()=>{const {game,r,act,a}=fixture();game.land(r,a,12);assert.equal(r.pendiente.tipo,'fuga');assert.equal(a.dinero,1000);const id=r.pendiente.id;assert.throws(()=>act(1,'tirarDadoFuga',{decisionId:id}));act(0,'tirarDadoFuga',{decisionId:id});assert.equal(a.dinero,0);assert.equal(a.posicion,12);assert.deepEqual(r.ultimaTirada.dados,[1]);assert.equal(r.ultimaTirada.tipo,'fuga');assert.equal(r.pendiente,null);assert.throws(()=>act(0,'tirarDadoFuga',{decisionId:id}));});
test('Fuga: el resguardo evita tirada y pago; el tiempo agotado resuelve el pago',()=>{const {game,r,a}=fixture();a.resguardoFuga=true;game.land(r,a,12);assert.equal(r.pendiente,null);assert.equal(a.dinero,1000);game.land(r,a,12);r.limiteTurno=0;game.tick();assert.equal(a.dinero,0);assert.equal(r.pendiente,null);});
test('FMI: Despido sindical mueve y cobra los intereses al compañero izquierdo',()=>{const {game,r,a,b}=fixture();b.deudaPersonal=5000;b.industriasCerradas=true;r.mazos.condiciones=[6];game.card(r,a,'condiciones');assert.equal(b.posicion,39);assert.equal(b.dinero,500);assert.equal(a.dinero,1000);assert.equal(b.industriasCerradas,false);assert.equal(r.interacciones.at(-1).origen,b.nombre);assert.equal(r.interacciones.at(-1).destino,'FMI');assert.match(r.interacciones.at(-1).detalle,/Intereses FMI/);});
test('FMI: sin deuda no cobra y No Pagar protege una sola visita',()=>{const {game,r,a,b}=fixture();r.mazos.condiciones=[6];game.card(r,a,'condiciones');assert.equal(b.dinero,1000);b.deudaPersonal=5000;b.noPagarVuelta=true;game.card(r,a,'condiciones');assert.equal(b.dinero,1000);game.card(r,a,'condiciones');assert.equal(b.dinero,500);});
test('Fuga 3D: un dado visible y resultado monetario, sin repetir animación',async()=>{const THREE=await import('three');const {createDiceTray}=await import('../public/board3d-dice.mjs');let label='';const tray=createDiceTray(new THREE.Scene(),s=>label=s);const roll={id:'fuga1',tipo:'fuga',jugador:'Staz',dados:[4],total:4};assert.equal(tray.sync(roll,true,0),true);tray.tick(900);assert.equal(tray.root.children.filter(c=>c.visible).length,1);assert.match(label,/4000/);assert.equal(tray.sync(roll,true,1000),false);tray.dispose();});

test('amortización: acepta importes pequeños y mayores de 5000 y muestra el pago real',()=>{const {r,act,a}=fixture();a.deudaPersonal=12000;a.dinero=15000;act(0,'pagarDeuda',{monto:125});assert.equal(a.deudaPersonal,11875);assert.equal(a.dinero,14875);act(0,'pagarDeuda',{monto:11875});assert.equal(a.deudaPersonal,0);assert.equal(a.dinero,3000);assert.equal(r.interacciones.at(-1).monto,11875);});
test('amortización: rechaza importes inválidos, sin fondos y fuera de turno o fase',()=>{const {game,r,act,a}=fixture();a.deudaPersonal=2000;for(const monto of [0,-1,1.5,'100',null,NaN,Infinity,2001,1001]){assert.throws(()=>act(0,'pagarDeuda',{monto}));assert.equal(a.deudaPersonal,2000);assert.equal(a.dinero,1000);}assert.throws(()=>act(1,'pagarDeuda',{monto:1}));game.land(r,a,12);assert.throws(()=>act(0,'pagarDeuda',{monto:1}));});
test('amortización: usa caja compartida sin reducir la deuda del aliado',()=>{const {act,a,b}=fixture();a.alianzaId=b.alianzaId='union';a.deudaPersonal=3000;b.deudaPersonal=4000;act(0,'pagarDeuda',{monto:250});assert.equal(a.dinero,750);assert.equal(b.dinero,750);assert.equal(a.deudaPersonal,2750);assert.equal(b.deudaPersonal,4000);});
