'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Game}=require('../lib/game');
function fixture(){const game=new Game({chooseIndex:()=>0,dice:()=>1});for(let i=0;i<2;i++)game.join('s'+i,{nombre:'Usuario '+i,userId:'usuario_'+i,sessionToken:String(i).repeat(64),sala:'AVISOS',crear:i===0});const r=game.rooms.AVISOS;const act=(i,event,data={})=>game.action('s'+i,event,{turnoId:r.turnoId,...data});act(0,'iniciarPartida',{monopolio:false});for(const player of r.jugadores)player.dinero=1000;return{game,r,act,a:r.jugadores[0],b:r.jugadores[1]};}
test('avisos: préstamo y amortización indican usuario, FMI e importe real',()=>{const {r,act}=fixture();act(0,'pedirPrestamo');let item=r.interacciones.at(-1);assert.equal(item.origen,'FMI');assert.equal(item.destino,'Usuario 0');assert.equal(item.accion,'Préstamo');assert.equal(item.monto,5000);act(0,'pagarDeuda');item=r.interacciones.at(-1);assert.equal(item.origen,'Usuario 0');assert.equal(item.destino,'FMI');assert.equal(item.accion,'Amortización');assert.equal(item.monto,5000);});
test('avisos: la renta solo aparece al pagar, una vez y para el dueño correcto',()=>{const {game,r,act,a,b}=fixture();game.payment(r,a,200,'Renta de Cobre',b.id,false);assert.equal(r.interacciones.length,0);act(0,'responderDecisionPago',{decisionId:r.pendiente.id,usarOro:false});assert.equal(r.interacciones.length,1);const item=r.interacciones[0];assert.equal(item.origen,a.nombre);assert.equal(item.destino,b.nombre);assert.equal(item.monto,200);assert.equal(item.accion,'Pago de renta');assert.equal(item.detalle,'Renta de Cobre');assert.equal(a.dinero,800);assert.equal(b.dinero,1200);});
test('avisos: pago en oro muestra un lingote y no simula un pago de efectivo',()=>{const {game,r,act,a}=fixture();game.payment(r,a,100,'Intereses FMI');act(0,'responderDecisionPago',{decisionId:r.pendiente.id,usarOro:true});assert.equal(r.interacciones.length,1);assert.equal(r.interacciones[0].monto,null);assert.equal(r.interacciones[0].destino,'FMI');assert.match(r.interacciones[0].detalle,/1 lingote/);assert.equal(a.dinero,1000);});
test('avisos: intercambio aceptado resume ambas partes sin duplicar cobros',()=>{const {game,r,act,a,b}=fixture();game.transfer(r,game.sur(r,'Cobre'),b.id);act(0,'proponerComercio',{destinatarioId:b.id,entrego:[],recibo:['Cobre'],pago:500,cobro:0});assert.equal(r.interacciones.length,0);act(1,'responderComercio',{decisionId:r.pendiente.id,aceptar:true});assert.equal(r.interacciones.length,1);const item=r.interacciones[0];assert.equal(item.accion,'Intercambio aceptado');assert.equal(item.origen,a.nombre);assert.equal(item.destino,b.nombre);assert.match(item.detalle,/Cobre/);assert.match(item.detalle,/\$500/);});
test('avisos: caja de alianza no duplica el movimiento y el historial es limitado y recuperable',()=>{const {game,r,a,b}=fixture();a.alianzaId=b.alianzaId='alianza';game.money(r,a,100);assert.equal(r.interacciones.length,1);assert.match(r.interacciones[0].destino,/alianza/);for(let i=0;i<70;i++)game.money(r,a,1);assert.equal(r.interacciones.length,60);assert.equal(new Set(r.interacciones.map(e=>e.id)).size,60);const restored=new Game({rooms:structuredClone(game.rooms)});assert.deepEqual(restored.state(restored.rooms.AVISOS).interacciones,r.interacciones);});
