const test=require('node:test'),assert=require('node:assert/strict');const {Game}=require('../lib/game');
function setup(){const g=new Game();for(let i=0;i<2;i++)g.join('s'+i,{nombre:'P'+i,userId:'presentation_'+i,sessionToken:String(i).repeat(64),sala:'PREVIEW',crear:i===0});const r=g.rooms.PREVIEW,p=r.jugadores[0];return{g,r,p};}
test('previsión FMI conserva dinero y exenciones; coincide con interés real',()=>{const {g,r,p}=setup();for(const [debt,rate,exempt]of [[12345,null,false],[30000,.2,false],[30000,.2,true],[0,null,false]]){Object.assign(p,{deudaPersonal:debt,interesEspecial:rate,noPagarVuelta:exempt});const before=structuredClone(p),view=g.state(r).jugadores[0];assert.equal(view.proximosIntereses,g.interest(structuredClone(p)));assert.deepEqual(p,before);}});
test('parejas y cadenas celebran el beneficio regional una vez, sin falso multiplicador',()=>{const {g,r,p}=setup();for(const id of [1,2]){g.transfer(r,r.tablero[id],p.id);r.tablero[id].industriasNac=1;}g.completedGroups(r);assert.equal(r.interacciones.at(-1).accion,'Pareja industrial');assert.equal(r.interacciones.at(-1).multiplicador,1.5);const count=r.interacciones.length;g.completedGroups(r);assert.equal(r.interacciones.length,count);g.transfer(r,r.tablero[3],p.id);r.tablero[3].industriasNac=1;g.completedGroups(r);assert.equal(r.interacciones.at(-1).accion,'Cadena industrial completa');assert.equal(r.interacciones.at(-1).multiplicador,undefined);assert.deepEqual(r.interacciones.at(-1).casillas,[1,2,3]);});
test('conexiones temporales se limpian al acabar y al sustituir la celebración',async()=>{const THREE=await import('three'),{createSetCelebration}=await import('../public/board3d-celebration.mjs');const scene=new THREE.Scene(),layer=createSetCelebration(scene);layer.start([1,2,3],'red',0);assert.equal(scene.children[0].children.length,2);assert.equal(layer.tick(1200),true);layer.start([9,11],'blue',1500);assert.equal(scene.children[0].children.length,1);assert.equal(layer.tick(4000),false);assert.equal(scene.children[0].children.length,0);layer.dispose();assert.equal(scene.children.length,0);});

test('ambiente: volumen independiente, fundidos, pausa y liberación de fuentes',()=>{
 const fs=require('node:fs'),vm=require('node:vm'),handlers={},sources=[],gains=[],storage={};const slider={value:'',addEventListener:(k,fn)=>handlers[k]=fn};
 const param=()=>({value:0,cancelScheduledValues(){},setTargetAtTime(v){this.value=v;}});const context={state:'running',sampleRate:100,currentTime:0,destination:{},createBuffer:(_,n)=>({getChannelData:()=>new Float32Array(n)}),createBufferSource(){const node={connect(){},disconnect(){},start(){},stop(){this.stopped=true;}};sources.push(node);return node;},createGain(){const node={gain:param(),connect(){},disconnect(){}};gains.push(node);return node;}};
 const sandbox={document:{hidden:false,getElementById:()=>slider},localStorage:{getItem:()=>null,setItem:(k,v)=>storage[k]=v},Math};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(require.resolve('../public/zone-audio.js'),'utf8'),sandbox);let enabled=true;const audio=sandbox.GameZoneAudio.create(()=>context,()=>enabled);
 audio.setZone('campo');assert.equal(sources.length,3);assert.ok(gains[0].gain.value>0);const full=gains[0].gain.value;audio.duck(2);assert.ok(gains[0].gain.value<full);context.currentTime=3;audio.setZone('campo');assert.equal(gains[0].gain.value,full);audio.setZone('costa');assert.equal(gains[0].gain.value,0);assert.ok(gains[1].gain.value>0);slider.value='0';handlers.input();assert.ok(gains.every(g=>g.gain.value===0));slider.value='50';handlers.input();assert.equal(storage.deuda_eterna_ambient,'0.5');audio.setZone(null);assert.ok(gains.every(g=>g.gain.value===0));enabled=false;audio.setZone('industria');assert.ok(gains.every(g=>g.gain.value===0));audio.stop();assert.ok(sources.every(s=>s.stopped));
});
