'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Game}=require('../lib/game');
function setup(start=true){let now=100000,dice=2;const game=new Game({now:()=>now,dice:()=>dice,chooseIndex:()=>0});for(let i=0;i<3;i++)game.join('s'+i,{nombre:'Jugador '+i,userId:'usuario_'+i,sessionToken:String(i).repeat(64),sala:'NUEVO',crear:i===0});const r=game.rooms.NUEVO;const act=(i,e,d={})=>game.action('s'+i,e,{turnoId:r.turnoId,...d});if(start)act(0,'iniciarPartida',{monopolio:false});return{game,r,act,advance:n=>{now+=n;game.tick();},setDice:n=>dice=n};}
test('pausa compartida conserva turno y plazo pendiente, rechaza acciones y sobrevive a guardado',()=>{const {game,r,act,advance}=setup();const p=r.jugadores[0];game.payment(r,p,3000,'Intereses FMI');r.pendiente.vence=110000;const deadline=r.limiteTurno,id=r.turnoId;act(1,'pausarPartida',{pausar:true});advance(400000);assert.equal(r.turnoId,id);assert.equal(r.pendiente.monto,3000);assert.throws(()=>act(0,'responderDecisionPago',{decisionId:r.pendiente.id,usarOro:true}),/pausada/);const saved=structuredClone(game.rooms);assert.equal(new Game({rooms:saved}).rooms.NUEVO.pausa.jugador,'Jugador 1');act(2,'pausarPartida',{pausar:false});assert.equal(r.limiteTurno,deadline+400000);assert.equal(r.pendiente.vence,510000);assert.equal(r.pausa,null);});
test('subasta reinicia diez segundos con cada puja y publica identidad e historial al vendedor',()=>{const {game,r,act,advance}=setup();const p=r.jugadores[0];p.deudaPersonal=30000;p.dinero=-100;r.tablero[1].dueño=p.id;act(0,'subastarPropiedad',{nombrePropiedad:'Azúcar'});const id=r.pendiente.id;advance(9000);act(1,'pujarSubasta',{decisionId:id,monto:500});advance(9000);assert.equal(r.fase,'subasta');act(2,'pujarSubasta',{decisionId:id,monto:600});assert.equal(game.state(r).pendiente.pujas.length,2);assert.equal(r.pendiente.pujas[1].nombre,'Jugador 2');advance(9999);assert.equal(r.fase,'subasta');advance(1);assert.notEqual(r.fase,'subasta');assert.equal(r.tablero[1].dueño,r.jugadores[2].id);assert.equal(p.dinero,500);});
test('FMI con deuda máxima admite lingote al pasar y en cartas de intereses del 15%',()=>{for(const card of [null,2,4]){const {game,r,act}=setup();const p=r.jugadores[0];p.deudaPersonal=30000;p.oro=2;p.dinero=0;if(card){r.mazos.condiciones=[card];game.card(r,p,'condiciones');}else game.payment(r,p,game.interest(p),'Intereses al pasar por el FMI');assert.equal(r.pendiente.oroPermitido,true);act(0,'responderDecisionPago',{decisionId:r.pendiente.id,usarOro:true});assert.equal(p.oro,1);assert.equal(p.deudaPersonal,30000);assert.equal(p.dinero,0);}});
test('tirada inicial requiere skin, no se repite y espera que cada jugador tire antes de iniciar',()=>{const {r,act,advance,setDice}=setup(false);assert.throws(()=>act(0,'tirarDadoInicial'),/personaje/);for(let i=0;i<3;i++)act(i,'seleccionarPersonaje',{personaje:['link','yoshi','kirby'][i]});act(0,'tirarDadoInicial');assert.equal(r.ultimaTirada.tipo,'inicial');assert.equal(r.jugadores[0].dinero,5400);assert.throws(()=>act(0,'tirarDadoInicial'),/Ya has/);assert.throws(()=>act(0,'iniciarPartida',{monopolio:false}),/Cada jugador/);advance(1400);setDice(6);act(1,'tirarDadoInicial');assert.throws(()=>act(2,'tirarDadoInicial'),/Espera/);advance(1400);setDice(1);act(2,'tirarDadoInicial');advance(1400);act(0,'iniciarPartida',{monopolio:false});assert.equal(r.turnoActual,1);assert.deepEqual(r.jugadores.map(p=>p.dinero),[5400,6200,5200]);});
test('completar cadena notifica una vez y permite recuperar una cadena perdida',()=>{const {game,r}=setup();const {GRUPOS_CADENAS}=require('../lib/data');const ids=Object.values(GRUPOS_CADENAS)[0];for(const id of ids)r.tablero[id].dueño=r.jugadores[0].id;game.publish(r);const item=r.interacciones.at(-1);assert.deepEqual(item.casillas,ids);assert.equal(item.multiplicador,ids.length);const n=r.interacciones.length;game.publish(r);assert.equal(r.interacciones.length,n);r.tablero[ids[0]].dueño=null;game.publish(r);r.tablero[ids[0]].dueño=r.jugadores[0].id;game.publish(r);assert.equal(r.interacciones.length,n+1);});
test('Fuga e inicio aceptan un dado tridimensional válido',async()=>{const {validRoll}=await import('../public/board3d-dice.mjs');for(const tipo of ['fuga','inicial'])assert.equal(validRoll({id:'x',tipo,dados:[4],total:4}),true);assert.equal(validRoll({id:'x',tipo:'inicial',dados:[9],total:9}),false);});
