'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Game,GameError}=require('../lib/game');
function fixture(){let time=1000;const game=new Game({now:()=>time,chooseIndex:()=>0,dice:()=>1});for(let i=0;i<3;i++)game.join('s'+i,{nombre:'Jugador '+i,userId:'usuario_'+i,sessionToken:String(i).repeat(64),sala:'TRADE',crear:i===0});const r=game.rooms.TRADE;const act=(i,event,data={})=>game.action('s'+i,event,{turnoId:r.turnoId,...data});act(0,'iniciarPartida',{monopolio:false});const [a,b,c]=r.jugadores;for(const player of r.jugadores)player.dinero=1000;game.transfer(r,game.sur(r,'Azúcar'),a.id);game.transfer(r,game.sur(r,'Cobre'),b.id);game.sur(r,'Cobre').industriasNac=2;game.north(r,game.sur(r,'Cobre')).industriasExp=1;game.transfer(r,game.sur(r,'Cobre'),b.id);const offer=(data={})=>act(0,'proponerComercio',{destinatarioId:b.id,entrego:[],recibo:['Cobre'],pago:500,cobro:0,...data});return {game,r,a,b,c,act,offer,advance:ms=>{time+=ms;game.tick();}};}
const reject=fn=>assert.throws(fn,GameError);
test('comercio: compra consensuada transfiere terreno, industrias y efectivo una sola vez',()=>{const {game,r,a,b,act,offer}=fixture();offer();assert.equal(game.sur(r,'Cobre').dueño,b.id);const id=r.pendiente.id;reject(()=>act(0,'responderComercio',{decisionId:id,aceptar:true}));reject(()=>act(2,'responderComercio',{decisionId:id,aceptar:true}));act(1,'responderComercio',{decisionId:id,aceptar:true});assert.equal(a.dinero,500);assert.equal(b.dinero,1500);assert.equal(game.sur(r,'Cobre').dueño,a.id);assert.equal(game.north(r,game.sur(r,'Cobre')).dueño,a.id);assert.equal(game.sur(r,'Cobre').industriasNac,2);assert.equal(game.north(r,game.sur(r,'Cobre')).industriasExp,1);assert.equal(r.fase,'tirada');reject(()=>act(1,'responderComercio',{decisionId:id,aceptar:true}));});
test('comercio: intercambio y venta funcionan en fase de gestión',()=>{for(const swap of [true,false]){const {game,r,a,b,act,offer}=fixture();r.fase='gestion';offer({entrego:['Azúcar'],recibo:swap?['Cobre']:[],pago:0,cobro:swap?0:250});act(1,'responderComercio',{decisionId:r.pendiente.id,aceptar:true});assert.equal(game.sur(r,'Azúcar').dueño,b.id);assert.equal(a.dinero,swap?1000:1250);if(swap)assert.equal(game.sur(r,'Cobre').dueño,a.id);assert.equal(r.fase,'gestion');}});
test('comercio: valida importes, propietarios, duplicados y turno',()=>{const {r,b,act,offer}=fixture();for(const data of [{pago:-1},{pago:0.5},{pago:Infinity},{pago:1001},{pago:500,cobro:1},{recibo:['Cobre','Cobre']},{recibo:['Azúcar']},{recibo:[],entrego:[]},{entrego:'Azúcar'},{recibo:['Cables']}])reject(()=>offer(data));reject(()=>act(1,'proponerComercio',{destinatarioId:r.jugadores[0].id,entrego:['Cobre'],recibo:[],pago:0,cobro:0}));b.conectado=false;reject(()=>offer());b.conectado=true;r.fase='pago';reject(()=>offer());});
test('comercio: rechazo, cancelación y caducidad nunca transfieren bienes',()=>{for(const mode of ['reject','cancel','expire']){const {game,r,a,b,act,offer,advance}=fixture();offer();const id=r.pendiente.id;if(mode==='expire')advance(60001);else act(mode==='cancel'?0:1,'responderComercio',{decisionId:id,aceptar:false});assert.equal(r.pendiente,null);assert.equal(r.fase,'tirada');assert.equal(a.dinero,1000);assert.equal(game.sur(r,'Cobre').dueño,b.id);}});
test('comercio: bloquea acciones durante la oferta y revalida saldo y propiedades al aceptar',()=>{const {game,r,a,b,act,offer}=fixture();offer();const id=r.pendiente.id;for(const event of ['tirarDado','terminarTurno','pedirPrestamo','construirIndustria'])reject(()=>act(0,event));a.dinero=0;reject(()=>act(1,'responderComercio',{decisionId:id,aceptar:true}));a.dinero=1000;game.sur(r,'Cobre').industriasNac=3;reject(()=>act(1,'responderComercio',{decisionId:id,aceptar:true}));assert.equal(b.dinero,1000);act(0,'responderComercio',{decisionId:id,aceptar:false});});
test('comercio: abandono cancela y desconexión no acepta automáticamente',()=>{const f=fixture();f.offer();f.game.leave('s1');assert.equal(f.r.pendiente,null);assert.equal(f.a.dinero,1000);const g=fixture();g.offer();g.game.disconnect('s0');reject(()=>g.act(1,'responderComercio',{decisionId:g.r.pendiente.id,aceptar:true}));g.advance(60001);assert.equal(g.r.pendiente,null);assert.equal(g.b.dinero,1000);});
test('comercio: las alianzas usan su caja común y no comercian consigo mismas',()=>{const {game,r,a,b,c,act,offer}=fixture();a.alianzaId=c.alianzaId='equipo';c.dinero=a.dinero;offer();act(1,'responderComercio',{decisionId:r.pendiente.id,aceptar:true});assert.equal(a.dinero,500);assert.equal(c.dinero,500);assert.ok(game.owns(r,c,game.sur(r,'Cobre')));reject(()=>offer({destinatarioId:c.id,recibo:['Cobre']}));});
test('comercio: oferta guardada se recupera y exige reconexión de ambas partes',()=>{const f=fixture();f.offer();const game=new Game({rooms:structuredClone(f.game.rooms),now:()=>2000});const r=game.rooms.TRADE;for(let i=0;i<2;i++)game.join('new'+i,{nombre:'Jugador '+i,userId:'usuario_'+i,sessionToken:String(i).repeat(64),sala:'TRADE'});game.action('new1','responderComercio',{turnoId:r.turnoId,decisionId:r.pendiente.id,aceptar:true});assert.equal(r.pendiente,null);assert.equal(r.jugadores[0].dinero,500);});
