'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {Game}=require('../lib/game');const World=require('../lib/world-events'),Rules=require('../public/world-events');
function setup(count=3){const g=new Game({dice:()=>1,chooseIndex:()=>0});for(let i=0;i<count;i++)g.join('s'+i,{nombre:'J'+i,userId:'events_user_'+i,sessionToken:String(i).repeat(64),sala:'EVENTOS',crear:i===0});g.action('s0','iniciarPartida',{monopolio:false});const r=g.rooms.EVENTOS,p=r.jugadores[0];r.turnoActual=0;g.beginTurn(r);const activate=id=>{r.eventoActual=null;r.mazoEventos=[id];World.activate(g,r,p);};const own=(id,who=p)=>{const c=r.tablero[id];g.transfer(r,c,who.id);c.industriasNac=1;const n=g.north(r,c);n.dueño=who.id;n.industriasExp=1;return c;};return{g,r,p,activate,own};}
test('12 eventos únicos, seis buenos/seis malos; mazo sin repetición hasta agotarse',()=>{const {g,r,p}=setup();assert.equal(Rules.catalog.length,12);assert.equal(Rules.catalog.filter(e=>e.positivo).length,6);const ids=[];for(let i=0;i<12;i++){r.eventoActual=null;World.activate(g,r,p);ids.push(r.eventoActual.id);}assert.equal(new Set(ids).size,12);assert.equal(g.state(r).mazoEventos,undefined);});
test('paso y caída en Salida activan, traslados no; FMI espera al pago y cruce restante',()=>{const {g,r,p}=setup();g.land(r,p,0);assert.equal(r.eventoActual,undefined);g.beginTurn(r);p.posicion=38;p.deudaPersonal=10000;g.roll(r,p);assert.equal(p.posicion,39);assert.equal(r.eventoActual,undefined);g.pay(r,p,{decisionId:r.pendiente.id,usarOro:true});assert.ok(r.eventoActual);const id=r.eventoActual.instancia;g.beginTurn(r);p.posicion=39;g.roll(r,p);assert.equal(r.eventoActual.instancia,id);});
test('duración: resto actual y siguiente turno del activador; cruces no renuevan',()=>{const {g,r,p,activate}=setup();activate('cosecha');const id=r.eventoActual.instancia;g.nextTurn(r);assert.equal(r.jugadores[r.turnoActual].id,r.jugadores[1].id);assert.equal(World.activate(g,r,r.jugadores[1]),false);g.nextTurn(r);g.nextTurn(r);assert.equal(r.jugadores[r.turnoActual].id,p.id);assert.equal(r.eventoActual.instancia,id);g.nextTurn(r);assert.equal(r.eventoActual,null);assert.equal(r.eventoCambio.tipo,'fin');});
test('salida del activador y desconexiones no prolongan el evento otra ronda',()=>{const {g,r,p,activate}=setup();activate('cosecha');g.nextTurn(r);r.jugadores.splice(0,1);r.turnoActual=0;g.nextTurn(r);g.nextTurn(r);assert.equal(r.eventoActual,null);const t=setup();t.activate('sequia');t.r.jugadores[1].conectado=false;t.g.nextTurn(t.r);assert.equal(t.r.jugadores[t.r.turnoActual].id,t.r.jugadores[2].id);assert.equal(t.r.eventoActual.pendientes.length,2);});
test('guardar y pausa conservan evento, revancha lo elimina',()=>{const {g,r,p,activate}=setup();activate('energia');const snap=structuredClone(r.eventoActual);g.action('s0','pausarPartida',{pausar:true});g.tick();assert.deepEqual(r.eventoActual,snap);const loaded=new Game({rooms:structuredClone(g.rooms)});assert.deepEqual(loaded.rooms.EVENTOS.eventoActual,snap);g.action('s0','pausarPartida',{pausar:false});g.finish(r,p.nombre,'Prueba');assert.equal(r.eventoActual,null);g.action('s0','prepararRevancha',{resultadoId:r.resultado.id});assert.equal(r.eventoCambio,null);assert.deepEqual(r.mazoEventos,[]);});
test('agricultura, pedidos y energía modifican solo cobros propios previstos',()=>{const {g,r,p,own,activate}=setup();for(const [event,id,mult]of [['cosecha',1,2],['sequia',1,.5],['pedidos',5,1.5],['cancelaciones',5,.5],['energia',17,2],['escasez',17,.5]]){const c=own(id);activate(event);const expected=Math.floor(c.precio*.5*mult);assert.equal(g.ownIncome(r,c),expected);assert.equal(g.rent(r,c),c.precio);const cash=p.dinero;g.land(r,p,id);assert.equal(p.dinero,cash+expected);}assert.equal(g.ownIncome(r,r.tablero[37]),1200);});
test('sanidad y metales reducen renta y cobro, respetan cadena y Norte',()=>{const {g,r,own,activate}=setup();own(9);own(11);activate('sanitaria');assert.equal(g.rent(r,r.tablero[9]),450);assert.equal(g.ownIncome(r,r.tablero[9]),225);assert.equal(g.rent(r,r.tablero[29]),900);own(13);activate('desplome');assert.equal(g.rent(r,r.tablero[13]),300);assert.equal(g.ownIncome(r,r.tablero[33]),600);});
test('mercados: banco paga, visitante exento, sin industrias/cierre no hay producción',()=>{const {g,r,p,own,activate}=setup();const q=r.jugadores[1];own(9,q);activate('mercados');const cash=q.dinero,visitor=p.dinero;g.land(r,p,9);assert.equal(q.dinero,cash+200);assert.equal(p.dinero,visitor);assert.equal(r.pendiente,null);q.industriasCerradas=true;g.land(r,p,9);assert.equal(q.dinero,cash+200);});
test('bono minero se paga una vez con efectivo; oro no crea bono',()=>{const {g,r,p,own,activate}=setup();const q=r.jugadores[1];own(13,q);activate('metales');let cash=q.dinero;g.land(r,p,13);const id=r.pendiente.id;g.pay(r,p,{decisionId:id,usarOro:false});assert.equal(q.dinero,cash+900);assert.throws(()=>g.pay(r,p,{decisionId:id,usarOro:false}));cash=q.dinero;g.land(r,p,33);g.pay(r,p,{decisionId:r.pendiente.id,usarOro:true});assert.equal(q.dinero,cash);});
test('costes aplican mejor descuento, recargos y primer uso solo tras compra válida',()=>{const {g,r,p,own,activate}=setup();const c=own(1);activate('cooperacion');const base=g.info(c).nac[1];assert.equal(g.buildCost(r,p,c,true),Math.floor(base*.7));r.descuento=true;assert.equal(g.buildCost(r,p,c,true),Math.floor(base*.5));p.dinero=0;assert.throws(()=>g.build(r,p,{nombrePropiedad:c.nombre,tipo:'nacional'}));assert.deepEqual(r.eventoActual.usados,[]);p.dinero=10000;g.build(r,p,{nombrePropiedad:c.nombre,tipo:'nacional'});assert.deepEqual(r.eventoActual.usados,[p.id]);r.descuento=false;assert.equal(g.buildCost(r,p,c,true),g.info(c).nac[2]);activate('energia');assert.equal(g.buildCost(r,p,c,true),Math.floor(g.info(c).nac[2]*.85));activate('escasez');r.descuento=true;assert.equal(g.buildCost(r,p,c,true),Math.floor(g.info(c).nac[2]*.5*1.15));activate('logistica');assert.equal(g.buildCost(r,p,c,false),Math.floor(g.info(c).exp[1]*.5*1.25));});
test('señalización coincide con la izquierda FMI; dos jugadores y quiebra',async()=>{const {seatLabels}=await import('../public/board3d-seats.mjs');const ps=[{id:'a'},{id:'b'},{id:'c'},{id:'d'}];const labels=seatLabels(ps,'a');assert.match(labels[1].relation,/izquierda/);assert.match(labels[3].relation,/derecha/);assert.match(seatLabels(ps.slice(0,2),'a')[1].relation,/izquierda y derecha/);ps[1].enQuiebra=true;assert.match(seatLabels(ps,'a')[2].relation,/izquierda/);});
