// The public landing renders independently of the game server and its wake-up time.
const host=document.getElementById('hero-world'),toggle=document.getElementById('hero-motion');
if(host&&!navigator.connection?.saveData)void boot();
async function boot(){try{
 const THREE=await import('three'),{GLTFLoader}=await import('/vendor/three/addons/loaders/GLTFLoader.js');
 const renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setSize(host.clientWidth,host.clientHeight);renderer.domElement.setAttribute('aria-hidden','true');
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,host.clientWidth/host.clientHeight,.1,100);camera.position.set(7,9,10.5);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0xfff1d0,0x305e50,3));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-3,9,5);scene.add(light);
 const world=new THREE.Group();scene.add(world);const mat=c=>new THREE.MeshStandardMaterial({color:c,roughness:.8});const wood=mat('#705033'),felt=mat('#204e3b'),ivory=mat('#f1e5bc');
 const base=new THREE.Mesh(new THREE.BoxGeometry(8,.45,8),wood);base.position.y=-.28;world.add(base);const center=new THREE.Mesh(new THREE.BoxGeometry(5.7,.08,5.7),felt);world.add(center);
 const positions=[];for(let i=0;i<5;i++){positions.push([-3.2+i*1.6,3.2],[-3.2+i*1.6,-3.2]);if(i>0&&i<4)positions.push([-3.2,-3.2+i*1.6],[3.2,-3.2+i*1.6]);}for(const [x,z]of positions){const tile=new THREE.Mesh(new THREE.BoxGeometry(1.47,.16,1.47),ivory);tile.position.set(x,.02,z);world.add(tile);}
 const files=['naturaleza/palmera','maquinaria/tractor','naturaleza/vaca','maquinaria/bomba-petrolera','industrial/fabrica-chocolate','industrial/planta-conservas','comercial/oficinas-fmi','maquinaria/caja-suministros'];const loader=new GLTFLoader();let loaded=0;
 for(const [i,file]of files.entries()){try{const obj=(await loader.loadAsync('/assets/modelos-3d/'+file+'.glb')).scene;obj.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(obj),size=bounds.getSize(new THREE.Vector3()),fit=Math.min(1.2/size.x,1.4/size.y,1.2/size.z),group=new THREE.Group();group.scale.setScalar(fit);obj.position.sub(new THREE.Vector3((bounds.min.x+bounds.max.x)/2,bounds.min.y,(bounds.min.z+bounds.max.z)/2));group.add(obj);const [x,z]=positions[[0,2,5,7,9,11,12,14][i]];group.position.set(x,.13,z);world.add(group);loaded++;}catch{}}
 if(!loaded){renderer.dispose();return;}
 host.append(renderer.domElement);host.classList.add('ready');let visible=true,frame=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,angle=0,target=0;
 function label(){toggle.textContent=paused?'Animar maqueta':'Pausar maqueta';toggle.setAttribute('aria-pressed',String(!paused));}toggle.hidden=false;label();toggle.onclick=()=>{paused=!paused;label();draw();};host.addEventListener('pointermove',e=>{if(paused)return;target=(e.clientX-host.getBoundingClientRect().left)/host.clientWidth-.5;draw();});host.addEventListener('pointerleave',()=>{target=0;});
 function draw(){if(frame||!visible||document.hidden)return;frame=requestAnimationFrame(t=>{frame=0;if(!paused){angle+=(target-angle)*.025;world.rotation.y=angle*.35+Math.sin(t*.00012)*.075;}renderer.render(scene,camera);if(!paused)draw();});}
 const observer=new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;if(visible)draw();});observer.observe(host);document.addEventListener('visibilitychange',()=>{if(!document.hidden)draw();});new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();draw();}).observe(host);draw();
 }catch{/* The real game screenshot remains usable without WebGL. */}}
